// AUTO-GENERATED by tools/nina_train_embedded_model.py
// Date: 2026-02-25 23:52:10
// Training data: 14567 blocks from ml_training_data.csv
//
// DO NOT EDIT MANUALLY — regenerate by running:
//   python3 tools/nina_train_embedded_model.py ~/.ninacatcoin/ml_training_data.csv
//
// This file contains ML model weights compiled directly into the daemon.
// All nodes use the exact same model = deterministic = no forks.

#pragma once

#include <cstdint>
#include <cmath>
#include <algorithm>
#include <string>

namespace ninacatcoin_ai {

// ============================================================================
// MODEL METADATA
// ============================================================================
struct EmbeddedModelInfo {
    static constexpr uint32_t TRAINING_BLOCKS = 14567;
    static constexpr const char* TRAINING_DATE = "2026-02-25 23:52:10";
    static constexpr uint32_t MODEL_VERSION = 1;
    static constexpr double TARGET_BLOCK_TIME = 120.0;  // seconds
};

// ============================================================================
// LEARNED STATISTICS FROM 14567 REAL BLOCKS
// ============================================================================
struct LearnedStatistics {
    // Solve time distribution
    static constexpr double SOLVE_TIME_MEAN    = 115.0330;
    static constexpr double SOLVE_TIME_MEDIAN  = 66.0000;
    static constexpr double SOLVE_TIME_STDEV   = 278.1255;
    static constexpr double SOLVE_TIME_P5      = 4.0;
    static constexpr double SOLVE_TIME_P95     = 365.0;
    static constexpr double SOLVE_TIME_P99     = 666.0;
    static constexpr double SOLVE_TIME_MIN     = 1.0;
    static constexpr double SOLVE_TIME_MAX     = 20055.0;

    // Hash entropy distribution
    static constexpr double ENTROPY_MEAN  = 59.0813;
    static constexpr double ENTROPY_STDEV = 1.9174;
    static constexpr int    ENTROPY_MIN   = 49;
    static constexpr int    ENTROPY_MAX   = 63;

    // Block size distribution
    static constexpr double BLOCK_SIZE_MEAN  = 742.0;
    static constexpr double BLOCK_SIZE_STDEV = 2379.7;
    static constexpr double BLOCK_SIZE_P95   = 4618.0;
    static constexpr double BLOCK_SIZE_P99   = 7891.0;

    // Difficulty change rate distribution
    static constexpr double DIFF_CHANGE_MEAN  = 0.276761;
    static constexpr double DIFF_CHANGE_STDEV = 0.882326;
    static constexpr double DIFF_CHANGE_P95   = 1.083632;
    static constexpr double DIFF_CHANGE_P99   = 5.112821;

    // Transaction stats
    static constexpr double TXS_MEAN = 1.16;
    static constexpr int    TXS_MAX  = 5;

    // Solve time ratio (solve_time / target_block_time)
    static constexpr double RATIO_MEAN  = 0.9586;
    static constexpr double RATIO_STDEV = 2.3177;
};

// ============================================================================
// ANOMALY DETECTION THRESHOLDS (learned from Isolation Forest + statistics)
// ============================================================================
struct AnomalyThresholds {
    // Z-score thresholds
    static constexpr double SOLVE_TIME_ZSCORE_WARN   = 2.0;
    static constexpr double SOLVE_TIME_ZSCORE_DANGER = 3.5;
    static constexpr double ENTROPY_ZSCORE_WARN      = 2.5;
    static constexpr double ENTROPY_ZSCORE_DANGER    = 4.0;
    static constexpr double DIFF_CHANGE_ZSCORE_WARN  = 2.0;
    static constexpr double DIFF_CHANGE_ZSCORE_DANGER= 3.0;

    // Absolute safety bounds
    static constexpr uint64_t SOLVE_TIME_MIN_SAFE = 1;
    static constexpr uint64_t SOLVE_TIME_MAX_SAFE = 1998;
    static constexpr uint64_t BLOCK_SIZE_MAX_SAFE = 500000;
    static constexpr int      ENTROPY_MIN_SAFE    = 44;

    // Isolation Forest approximation parameters
    static constexpr double IFOREST_THRESHOLD = 0.000000;
    static constexpr double SCALER_MEAN_RATIO   = 0.958605;
    static constexpr double SCALER_MEAN_DIFF    = 2.201189;
    static constexpr double SCALER_MEAN_ENTROPY = 59.081359;
    static constexpr double SCALER_STD_RATIO    = 2.317713;
    static constexpr double SCALER_STD_DIFF     = 158.574585;
    static constexpr double SCALER_STD_ENTROPY  = 1.917427;
    static constexpr bool   HAS_IFOREST = true;
    static constexpr double ANOMALY_RATIO_BOUNDARY = 2.211655;
    static constexpr double ANOMALY_DIFF_BOUNDARY  = 0.923976;

};

// ============================================================================
// DIFFICULTY PREDICTION MODEL (Linear Regression, trained on 14567 blocks)
// predicted_diff_change = intercept + avg_solve_ratio * coeff_ratio + trend * coeff_trend
// ============================================================================
struct DifficultyPredictor {
    static constexpr double INTERCEPT       = 0.0727982964;
    static constexpr double COEFF_AVG_RATIO = -0.0060617583;
    static constexpr double COEFF_TREND     = 0.0036728338;

    /**
     * Predict difficulty change ratio from recent block data.
     * @param avg_solve_ratio  Average(recent_solve_times) / TARGET_BLOCK_TIME
     * @param trend            (avg_second_half - avg_first_half) / TARGET_BLOCK_TIME
     * @return predicted difficulty change as ratio (-1 to +1 typically)
     */
    static double predict_change(double avg_solve_ratio, double trend) {
        return INTERCEPT + COEFF_AVG_RATIO * avg_solve_ratio + COEFF_TREND * trend;
    }
};

// ============================================================================
// EMBEDDED ANOMALY SCORER
// Pure C++ inference — no Python, no sockets, no external dependencies.
// Every node computes the same score = deterministic = no forks.
// ============================================================================

enum class AnomalyLevel {
    SAFE       = 0,   // Normal block, no concerns
    NOTICE     = 1,   // Slightly unusual, log only
    WARNING    = 2,   // Suspicious, worth investigating
    DANGEROUS  = 3    // Highly anomalous, potential attack
};

struct AnomalyResult {
    double    confidence;       // 0.0 (no data) to 1.0 (certain)
    double    risk_score;       // 0.0 (safe) to 1.0 (dangerous)
    AnomalyLevel level;
    int       anomaly_flags;    // Bitfield of which features triggered

    // Anomaly flag bits
    static constexpr int FLAG_FAST_SOLVE    = 0x01;
    static constexpr int FLAG_SLOW_SOLVE    = 0x02;
    static constexpr int FLAG_LOW_ENTROPY   = 0x04;
    static constexpr int FLAG_HIGH_DIFF_CHG = 0x08;
    static constexpr int FLAG_LARGE_BLOCK   = 0x10;
    static constexpr int FLAG_IFOREST       = 0x20;

    std::string describe() const {
        std::string desc;
        if (anomaly_flags & FLAG_FAST_SOLVE)    desc += "FAST_SOLVE ";
        if (anomaly_flags & FLAG_SLOW_SOLVE)    desc += "SLOW_SOLVE ";
        if (anomaly_flags & FLAG_LOW_ENTROPY)   desc += "LOW_ENTROPY ";
        if (anomaly_flags & FLAG_HIGH_DIFF_CHG) desc += "HIGH_DIFF_CHANGE ";
        if (anomaly_flags & FLAG_LARGE_BLOCK)   desc += "LARGE_BLOCK ";
        if (anomaly_flags & FLAG_IFOREST)       desc += "IFOREST_ANOMALY ";
        if (desc.empty()) desc = "NORMAL";
        return desc;
    }
};

/**
 * Score a block for anomalies using the embedded model.
 * This is the main entry point — called for every new block.
 *
 * IMPORTANT: This is ADVISORY ONLY. It NEVER rejects blocks.
 * It provides confidence/risk scores for NINA's learning system.
 *
 * @param solve_time         Time to solve this block (seconds)
 * @param difficulty         Current block difficulty
 * @param prev_difficulty    Previous block difficulty
 * @param hash_entropy       Bit entropy of block hash (0-64)
 * @param block_size_bytes   Size of the block in bytes
 * @param txs_count          Number of transactions
 * @return AnomalyResult with scores and flags
 */
inline AnomalyResult score_block_anomaly(
    uint64_t solve_time,
    uint64_t difficulty,
    uint64_t prev_difficulty,
    uint32_t hash_entropy,
    uint64_t block_size_bytes,
    uint32_t txs_count
) {
    AnomalyResult result;
    result.confidence = 0.0;
    result.risk_score = 0.0;
    result.level = AnomalyLevel::SAFE;
    result.anomaly_flags = 0;

    // Need valid data
    if (solve_time == 0) return result;

    double risk_components = 0.0;
    int num_checks = 0;

    // ===== CHECK 1: Solve time Z-score =====
    double solve_zscore = std::abs(
        (static_cast<double>(solve_time) - LearnedStatistics::SOLVE_TIME_MEAN) /
        LearnedStatistics::SOLVE_TIME_STDEV
    );
    num_checks++;

    if (solve_time < AnomalyThresholds::SOLVE_TIME_MIN_SAFE) {
        result.anomaly_flags |= AnomalyResult::FLAG_FAST_SOLVE;
        risk_components += 0.8;  // Very fast = high risk
    } else if (solve_zscore > AnomalyThresholds::SOLVE_TIME_ZSCORE_DANGER) {
        if (solve_time < LearnedStatistics::SOLVE_TIME_MEAN) {
            result.anomaly_flags |= AnomalyResult::FLAG_FAST_SOLVE;
        } else {
            result.anomaly_flags |= AnomalyResult::FLAG_SLOW_SOLVE;
        }
        risk_components += 0.6;
    } else if (solve_zscore > AnomalyThresholds::SOLVE_TIME_ZSCORE_WARN) {
        risk_components += 0.2;
    } else {
        risk_components += 0.0;  // Normal
    }

    // ===== CHECK 2: Hash entropy =====
    double entropy_zscore = std::abs(
        (static_cast<double>(hash_entropy) - LearnedStatistics::ENTROPY_MEAN) /
        std::max(LearnedStatistics::ENTROPY_STDEV, 0.1)
    );
    num_checks++;

    if (hash_entropy < static_cast<uint32_t>(AnomalyThresholds::ENTROPY_MIN_SAFE)) {
        result.anomaly_flags |= AnomalyResult::FLAG_LOW_ENTROPY;
        risk_components += 0.7;
    } else if (entropy_zscore > AnomalyThresholds::ENTROPY_ZSCORE_DANGER) {
        result.anomaly_flags |= AnomalyResult::FLAG_LOW_ENTROPY;
        risk_components += 0.4;
    } else if (entropy_zscore > AnomalyThresholds::ENTROPY_ZSCORE_WARN) {
        risk_components += 0.1;
    }

    // ===== CHECK 3: Difficulty change rate =====
    if (prev_difficulty > 0) {
        double diff_change = std::abs(
            static_cast<double>(difficulty) - static_cast<double>(prev_difficulty)
        ) / static_cast<double>(prev_difficulty);

        double diff_zscore = std::abs(
            (diff_change - LearnedStatistics::DIFF_CHANGE_MEAN) /
            std::max(LearnedStatistics::DIFF_CHANGE_STDEV, 0.001)
        );
        num_checks++;

        if (diff_zscore > AnomalyThresholds::DIFF_CHANGE_ZSCORE_DANGER) {
            result.anomaly_flags |= AnomalyResult::FLAG_HIGH_DIFF_CHG;
            risk_components += 0.5;
        } else if (diff_zscore > AnomalyThresholds::DIFF_CHANGE_ZSCORE_WARN) {
            risk_components += 0.15;
        }
    }

    // ===== CHECK 4: Block size =====
    if (block_size_bytes > AnomalyThresholds::BLOCK_SIZE_MAX_SAFE) {
        result.anomaly_flags |= AnomalyResult::FLAG_LARGE_BLOCK;
        risk_components += 0.4;
        num_checks++;
    } else {
        num_checks++;
    }

    // ===== FINAL SCORING =====
    if (num_checks > 0) {
        result.risk_score = std::min(1.0, risk_components / num_checks);
        result.confidence = std::min(1.0, static_cast<double>(EmbeddedModelInfo::TRAINING_BLOCKS) / 1000.0);

        // Determine anomaly level
        if (result.risk_score >= 0.6) {
            result.level = AnomalyLevel::DANGEROUS;
        } else if (result.risk_score >= 0.3) {
            result.level = AnomalyLevel::WARNING;
        } else if (result.risk_score >= 0.1) {
            result.level = AnomalyLevel::NOTICE;
        } else {
            result.level = AnomalyLevel::SAFE;
        }
    }

    return result;
}

/**
 * Predict expected solve time ratio for the next block.
 * Uses the embedded linear regression model.
 *
 * @param recent_solve_times  Array of recent solve times (at least 5)
 * @param count               Number of elements in the array
 * @return Predicted difficulty change ratio
 */
inline double predict_difficulty_change(const uint64_t* recent_solve_times, size_t count) {
    if (count < 5) return 0.0;

    constexpr double TARGET = EmbeddedModelInfo::TARGET_BLOCK_TIME;

    // Calculate average solve time ratio
    double sum = 0.0;
    for (size_t i = 0; i < count; i++) {
        sum += static_cast<double>(recent_solve_times[i]);
    }
    double avg_ratio = (sum / count) / TARGET;

    // Calculate trend
    size_t half = count / 2;
    double first_half_sum = 0.0, second_half_sum = 0.0;
    for (size_t i = 0; i < half; i++) first_half_sum += static_cast<double>(recent_solve_times[i]);
    for (size_t i = half; i < count; i++) second_half_sum += static_cast<double>(recent_solve_times[i]);
    double trend = ((second_half_sum / (count - half)) - (first_half_sum / half)) / TARGET;

    return DifficultyPredictor::predict_change(avg_ratio, trend);
}

} // namespace ninacatcoin_ai
