# CMake generated Testfile for 
# Source directory: /mnt/i/ninacatcoin/src
# Build directory: /mnt/i/ninacatcoin/build-linux/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("common")
subdirs("crypto")
subdirs("ringct")
subdirs("checkpoints")
subdirs("ai")
subdirs("cryptonote_basic")
subdirs("cryptonote_core")
subdirs("lmdb")
subdirs("multisig")
subdirs("net")
subdirs("hardforks")
subdirs("blockchain_db")
subdirs("mnemonics")
subdirs("rpc")
subdirs("seraphis_crypto")
subdirs("serialization")
subdirs("wallet")
subdirs("p2p")
subdirs("cryptonote_protocol")
subdirs("simplewallet")
subdirs("genesis")
subdirs("gen_multisig")
subdirs("gen_ssl_cert")
subdirs("daemonizer")
subdirs("daemon")
subdirs("blockchain_utilities")
subdirs("blocks")
subdirs("device")
subdirs("device_trezor")
