// AUTO-GENERATED by cmake/GenerateAIHash.cmake — DO NOT EDIT
// Regenerated every time AI source files change.
//
// This hash is compiled into the binary so all nodes running
// the same version can verify each other's code integrity via P2P.
//
// Build timestamp: 2026-02-21 02:49:28 UTC
// Files hashed: 19

#pragma once

namespace ninacatcoin_ai {

// SHA-256 of all AI source files, calculated at compile time
static constexpr const char* AI_COMPILED_CODE_HASH =
    "2dce760f88b9a7950cefcd5b0da5eceec79a18198a136a91f169a20b3a9a772f";

// Number of source files included in the hash
static constexpr int AI_COMPILED_FILE_COUNT = 19;

// Build timestamp for this hash
static constexpr const char* AI_HASH_BUILD_TIME =
    "2026-02-21 02:49:28 UTC";

} // namespace ninacatcoin_ai
