// AUTO-GENERATED by cmake/GenerateAIHash.cmake — DO NOT EDIT
// Regenerated every time AI source files change.
//
// This hash is compiled into the binary so all nodes running
// the same version can verify each other's code integrity via P2P.
//
// Build timestamp: 2026-02-20 16:28:28 UTC
// Files hashed: 19

#pragma once

namespace ninacatcoin_ai {

// SHA-256 of all AI source files, calculated at compile time
static constexpr const char* AI_COMPILED_CODE_HASH =
    "9d14c3e5a15d3b4e7e997ed53b0b4b8ab6f0dc956c9cacaad54837c5aa3b918a";

// Number of source files included in the hash
static constexpr int AI_COMPILED_FILE_COUNT = 19;

// Build timestamp for this hash
static constexpr const char* AI_HASH_BUILD_TIME =
    "2026-02-20 16:28:28 UTC";

} // namespace ninacatcoin_ai
