// AUTO-GENERATED by cmake/GenerateAIHash.cmake — DO NOT EDIT
// Regenerated every time AI source files change.
//
// This hash is compiled into the binary so all nodes running
// the same version can verify each other's code integrity via P2P.
//
// Build timestamp: 2026-02-20 17:03:23 UTC
// Files hashed: 19

#pragma once

namespace ninacatcoin_ai {

// SHA-256 of all AI source files, calculated at compile time
static constexpr const char* AI_COMPILED_CODE_HASH =
    "63049b7cb230722e61d2ccb8b098024bd29e50075faf60b5c4fbe449c9331b71";

// Number of source files included in the hash
static constexpr int AI_COMPILED_FILE_COUNT = 19;

// Build timestamp for this hash
static constexpr const char* AI_HASH_BUILD_TIME =
    "2026-02-20 17:03:23 UTC";

} // namespace ninacatcoin_ai
