// AUTO-GENERATED by cmake/GenerateFullHash.cmake — DO NOT EDIT
// Regenerated every time ANY source file changes.
//
// This hash covers ALL source files that compose the ninacatcoin daemon binary.
// At runtime, the daemon recalculates this hash. If it differs, the source
// has been tampered with and auto-remediation from GitHub is triggered.
//
// Build timestamp: 2026-02-21 05:56:26 UTC
// Files hashed: 634

#pragma once

namespace ninacatcoin_integrity {

// SHA-256 of ALL source files, calculated at compile time
static constexpr const char* FULL_COMPILED_SOURCE_HASH =
    "7cd38a6c06031bc5891b087061ccd1494156ab8c5f5542cf688b7a94d07f1786";

// Number of source files included in the hash
static constexpr int FULL_COMPILED_FILE_COUNT = 634;

// Build timestamp for this hash
static constexpr const char* FULL_HASH_BUILD_TIME =
    "2026-02-21 05:56:26 UTC";

} // namespace ninacatcoin_integrity
