// AUTO-GENERATED by cmake/GenerateFullHash.cmake — DO NOT EDIT
// Regenerated every time ANY source file changes.
//
// This hash covers ALL source files that compose the ninacatcoin daemon binary.
// At runtime, the daemon recalculates this hash. If it differs, the source
// has been tampered with and auto-remediation from GitHub is triggered.
//
// Build timestamp: 2026-02-21 05:31:39 UTC
// Files hashed: 634

#pragma once

namespace ninacatcoin_integrity {

// SHA-256 of ALL source files, calculated at compile time
static constexpr const char* FULL_COMPILED_SOURCE_HASH =
    "9a373a520610f5cbbeec2de68d0caba68813797c906b96754243c0aee40393b4";

// Number of source files included in the hash
static constexpr int FULL_COMPILED_FILE_COUNT = 634;

// Build timestamp for this hash
static constexpr const char* FULL_HASH_BUILD_TIME =
    "2026-02-21 05:31:39 UTC";

} // namespace ninacatcoin_integrity
