# Copyright (c) 2026, The ninacatcoin Project
#
# Script executed at build time to:
#   1. Read list of ALL source files from a filelist
#   2. Concatenate all source files
#   3. Calculate SHA-256 of the concatenation
#   4. Generate full_source_hash.h with the hash as constexpr
#
# Usage: cmake -DAI_FILELIST="path/filelist.txt" -DOUTPUT_FILE="path/full_source_hash.h" -DHASH_TYPE=FULL -P GenerateFullHash.cmake

cmake_minimum_required(VERSION 3.10)

# Read file list (one path per line)
if(NOT EXISTS "${AI_FILELIST}")
    message(FATAL_ERROR "[Full Integrity] Filelist not found: ${AI_FILELIST}")
endif()

file(READ "${AI_FILELIST}" FILELIST_RAW)
# Convert newlines to semicolons (CMake list format)
string(REPLACE "\n" ";" FILE_LIST "${FILELIST_RAW}")

# Concatenate all file contents into one string for hashing
set(COMBINED_CONTENT "")
set(FILE_COUNT 0)

foreach(SRC_FILE ${FILE_LIST})
    # Skip empty entries
    string(STRIP "${SRC_FILE}" SRC_FILE)
    if("${SRC_FILE}" STREQUAL "")
        continue()
    endif()
    if(EXISTS "${SRC_FILE}")
        file(READ "${SRC_FILE}" FILE_CONTENT)
        string(APPEND COMBINED_CONTENT "${FILE_CONTENT}")
        math(EXPR FILE_COUNT "${FILE_COUNT} + 1")
    else()
        message(WARNING "[Full Integrity] File not found: ${SRC_FILE}")
    endif()
endforeach()

# Calculate SHA-256 hash of combined content
string(SHA256 FULL_SOURCE_HASH "${COMBINED_CONTENT}")

# Get current timestamp
string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%d %H:%M:%S UTC" UTC)

# Generate the header file
file(WRITE "${OUTPUT_FILE}"
"// AUTO-GENERATED by cmake/GenerateFullHash.cmake — DO NOT EDIT
// Regenerated every time ANY source file changes.
//
// This hash covers ALL source files that compose the ninacatcoin daemon binary.
// At runtime, the daemon recalculates this hash. If it differs, the source
// has been tampered with and auto-remediation from GitHub is triggered.
//
// Build timestamp: ${BUILD_TIMESTAMP}
// Files hashed: ${FILE_COUNT}

#pragma once

namespace ninacatcoin_integrity {

// SHA-256 of ALL source files, calculated at compile time
static constexpr const char* FULL_COMPILED_SOURCE_HASH =
    \"${FULL_SOURCE_HASH}\";

// Number of source files included in the hash
static constexpr int FULL_COMPILED_FILE_COUNT = ${FILE_COUNT};

// Build timestamp for this hash
static constexpr const char* FULL_HASH_BUILD_TIME =
    \"${BUILD_TIMESTAMP}\";

} // namespace ninacatcoin_integrity
")

message(STATUS "[Full Integrity] Hash: ${FULL_SOURCE_HASH}")
message(STATUS "[Full Integrity] Files: ${FILE_COUNT}")
