# Copyright (c) 2026, The ninacatcoin Project
#
# Script executed at build time to:
#   1. Read list of AI source files from a filelist
#   2. Concatenate all AI source files
#   3. Calculate SHA-256 of the concatenation
#   4. Generate ai_code_hash.h with the hash as constexpr
#
# Usage: cmake -DAI_FILELIST="path/filelist.txt" -DOUTPUT_FILE="path/ai_code_hash.h" -P GenerateAIHash.cmake

cmake_minimum_required(VERSION 3.10)

# Read file list (one path per line)
if(NOT EXISTS "${AI_FILELIST}")
    message(FATAL_ERROR "[AI Integrity] Filelist not found: ${AI_FILELIST}")
endif()

file(READ "${AI_FILELIST}" AI_FILELIST_RAW)
# Convert newlines to semicolons (CMake list format)
string(REPLACE "\n" ";" AI_FILE_LIST "${AI_FILELIST_RAW}")

# Concatenate all file contents into one string for hashing
set(COMBINED_CONTENT "")
set(FILE_COUNT 0)

foreach(AI_FILE ${AI_FILE_LIST})
    # Skip empty entries
    string(STRIP "${AI_FILE}" AI_FILE)
    if("${AI_FILE}" STREQUAL "")
        continue()
    endif()
    if(EXISTS "${AI_FILE}")
        file(READ "${AI_FILE}" FILE_CONTENT)
        string(APPEND COMBINED_CONTENT "${FILE_CONTENT}")
        math(EXPR FILE_COUNT "${FILE_COUNT} + 1")
    else()
        message(WARNING "[AI Integrity] File not found: ${AI_FILE}")
    endif()
endforeach()

# Calculate SHA-256 hash of combined content
string(SHA256 AI_CODE_HASH "${COMBINED_CONTENT}")

# Get current timestamp
string(TIMESTAMP BUILD_TIMESTAMP "%Y-%m-%d %H:%M:%S UTC" UTC)

# Generate the header file
file(WRITE "${OUTPUT_FILE}"
"// AUTO-GENERATED by cmake/GenerateAIHash.cmake — DO NOT EDIT
// Regenerated every time AI source files change.
//
// This hash is compiled into the binary so all nodes running
// the same version can verify each other's code integrity via P2P.
//
// Build timestamp: ${BUILD_TIMESTAMP}
// Files hashed: ${FILE_COUNT}

#pragma once

namespace ninacatcoin_ai {

// SHA-256 of all AI source files, calculated at compile time
static constexpr const char* AI_COMPILED_CODE_HASH =
    \"${AI_CODE_HASH}\";

// Number of source files included in the hash
static constexpr int AI_COMPILED_FILE_COUNT = ${FILE_COUNT};

// Build timestamp for this hash
static constexpr const char* AI_HASH_BUILD_TIME =
    \"${BUILD_TIMESTAMP}\";

} // namespace ninacatcoin_ai
")

message(STATUS "[AI Integrity] Hash: ${AI_CODE_HASH}")
message(STATUS "[AI Integrity] Files: ${FILE_COUNT}")
